name: Launchers
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
jobs:
  generate-launchers:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        scalaJsVersion: ["1.9.0", "1.10.0"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: 8
      - run: |
          ./mill -i "native[$scalaJsVersion].writeNativeImageScript" generate.sh "" && \
          ./generate.sh && \
          ./mill -i "native[$scalaJsVersion].copyToArtifacts" artifacts/
        if: runner.os != 'Windows'
        env:
          scalaJsVersion: ${{ matrix.scalaJsVersion }}
      - run: |
          @call ./mill.bat -i "native[%scalaJsVersion%].writeNativeImageScript" generate.bat ""
          @call generate.bat
          @call ./mill.bat -i "native[%scalaJsVersion%].copyToArtifacts" artifacts/
        shell: cmd
        if: runner.os == 'Windows'
        env:
          scalaJsVersion: ${{ matrix.scalaJsVersion }}
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: launcher-${{ matrix.os }}
          path: artifacts/
          if-no-files-found: error
          retention-days: 1
      - run: ./mill -i upload artifacts/
        if: github.event_name == 'push'
        env:
          UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-static-launcher:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaJsVersion: ["1.9.0", "1.10.0"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: 8
      - run: |
          ./mill -i "native-static[$scalaJsVersion].writeNativeImageScript" generate.sh "" && \
          ./generate.sh && \
          ./mill -i "native-static[$scalaJsVersion].copyToArtifacts" artifacts/
        env:
          scalaJsVersion: ${{ matrix.scalaJsVersion }}
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: launcher-${{ matrix.os }}-static
          path: artifacts/
          if-no-files-found: error
          retention-days: 1
      - run: ./mill -i upload artifacts/
        if: github.event_name == 'push'
        env:
          UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-mostly-static-launcher:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaJsVersion: ["1.9.0", "1.10.0"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: 8
      - run: |
          ./mill -i "native-mostly-static[$scalaJsVersion].writeNativeImageScript" generate.sh "" && \
          ./generate.sh && \
          ./mill -i "native-mostly-static[$scalaJsVersion].copyToArtifacts" artifacts/
        env:
          scalaJsVersion: ${{ matrix.scalaJsVersion }}
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: launcher-${{ matrix.os }}-mostly-static
          path: artifacts/
          if-no-files-found: error
          retention-days: 1
      - run: ./mill -i upload artifacts/
        if: github.event_name == 'push'
        env:
          UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
